---

- name: Nginx is installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - nginx
  - python-passlib

- name: Default site is not available
  file:
    name: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Nginx is started
  service:
    name: nginx
    state: started
